#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18034
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Data.Linq;
using System.Data.Linq.Mapping;
using System.Linq;
using System.Linq.Expressions;
using System.Reflection;



[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="gaymerdb")]
public partial class GaymerLINQDataContext : System.Data.Linq.DataContext
{
	
	private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
	
  #region Extensibility Method Definitions
  partial void OnCreated();
  partial void InsertSlettMeg(SlettMeg instance);
  partial void UpdateSlettMeg(SlettMeg instance);
  partial void DeleteSlettMeg(SlettMeg instance);
  #endregion
	
	public GaymerLINQDataContext() : 
			base(global::System.Configuration.ConfigurationManager.ConnectionStrings["gaymerdbConnectionString"].ConnectionString, mappingSource)
	{
		OnCreated();
	}
	
	public GaymerLINQDataContext(string connection) : 
			base(connection, mappingSource)
	{
		OnCreated();
	}
	
	public GaymerLINQDataContext(System.Data.IDbConnection connection) : 
			base(connection, mappingSource)
	{
		OnCreated();
	}
	
	public GaymerLINQDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
			base(connection, mappingSource)
	{
		OnCreated();
	}
	
	public GaymerLINQDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
			base(connection, mappingSource)
	{
		OnCreated();
	}
	
	public System.Data.Linq.Table<SlettMeg> SlettMegs
	{
		get
		{
			return this.GetTable<SlettMeg>();
		}
	}
}

[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.SlettMeg")]
public partial class SlettMeg : INotifyPropertyChanging, INotifyPropertyChanged
{
	
	private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
	
	private int _sda;
	
	private string _jall;
	
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnsdaChanging(int value);
    partial void OnsdaChanged();
    partial void OnjallChanging(string value);
    partial void OnjallChanged();
    #endregion
	
	public SlettMeg()
	{
		OnCreated();
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_sda", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
	public int sda
	{
		get
		{
			return this._sda;
		}
		set
		{
			if ((this._sda != value))
			{
				this.OnsdaChanging(value);
				this.SendPropertyChanging();
				this._sda = value;
				this.SendPropertyChanged("sda");
				this.OnsdaChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_jall", DbType="NChar(10)")]
	public string jall
	{
		get
		{
			return this._jall;
		}
		set
		{
			if ((this._jall != value))
			{
				this.OnjallChanging(value);
				this.SendPropertyChanging();
				this._jall = value;
				this.SendPropertyChanged("jall");
				this.OnjallChanged();
			}
		}
	}
	
	public event PropertyChangingEventHandler PropertyChanging;
	
	public event PropertyChangedEventHandler PropertyChanged;
	
	protected virtual void SendPropertyChanging()
	{
		if ((this.PropertyChanging != null))
		{
			this.PropertyChanging(this, emptyChangingEventArgs);
		}
	}
	
	protected virtual void SendPropertyChanged(String propertyName)
	{
		if ((this.PropertyChanged != null))
		{
			this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
		}
	}
}
#pragma warning restore 1591
